spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog-master.xml
jwt:
  secret: rastishka_na_virost_2024
  lifetime: 60m